export const ALL_TODO_REQUEST = "ALL_TODO_REQUEST";
export const ALL_TODO_SUCCESS = "ALL_TODO_SUCCESS";
export const ALL_TODO_FAIL = "ALL_TODO_FAIL";

export const ADMIN_TODO_REQUEST = "ADMIN_TODO_REQUEST";
export const ADMIN_TODO_SUCCESS = "ADMIN_TODO_SUCCESS";
export const ADMIN_TODO_FAIL = "ADMIN_TODO_FAIL";

export const NEW_TODO_REQUEST = "NEW_TODO_REQUEST";
export const NEW_TODO_SUCCESS = "NEW_TODO_SUCCESS";
export const NEW_TODO_RESET = "NEW_TODO_RESET";
export const NEW_TODO_FAIL = "NEW_TODO_FAIL";

export const MY_TODO_REQUEST = "MY_TODO_REQUEST";
export const MY_TODO_SUCCESS = "MY_TODO_SUCCESS";
export const MY_TODO_FAIL = "MY_TODO_FAIL";

export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_RESET = "UPDATE_TODO_RESET";
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_RESET = "DELETE_TODO_RESET";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";

export const TODO_DETAILS_REQUEST = "TODO_DETAILS_REQUEST";
export const TODO_DETAILS_SUCCESS = "TODO_DETAILS_SUCCESS";
export const TODO_DETAILS_FAIL = "TODO_DETAILS_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";